### ISSUE TITLE
make install should install _build/consumer/processor.native

### ISSUE THREAD

**Issue by UnixJunkie** [Antique-team/clangml#58]
in opam's bin dir, for example.

**Comment by dsheets** [comment]
You could also simply package `clangml.install` with the rest of the release. Using a `.install` file will let opam take care of the uninstallation as well.

**Comment by UnixJunkie** [comment]
there is a .install in the opam package

**Comment by UnixJunkie** [comment]
# cat clangml.3.6.0.2/files/clangml.install 
    bin: [
      "_build/consumer/processor.native" {"clangml-processor"}
    ]
